### ISSUE TITLE
Show suitable multiplier bonuses in leaderboards

### ISSUE THREAD

**Issue by benedfit** [newhighsco/destiny-clan-warfare#121]
Some modifiers, such as the number of weapons used for “Spice of Life” would be useful to display for some events

**Comment by mattybeard** [comment]
We could show it at match level but it wouldn't roll up very well? Is that a fair compromise?

**Comment by mattybeard** [comment]
Added it - not sure there is much more I can do from here.

**Comment by benedfit** [comment]
I think it's probably better to leave them off entirely rather than only show them in some instances
