### ISSUE TITLE
Beta tester badges

### ISSUE THREAD

**Issue by benedfit** [newhighsco/destiny-clan-warfare#13]
# Confirmed

- [x] Diamond Duck - Avalanche UK
- [x] brad1ley - Avalanche UK
- [x] Purple Raine - Avalanche UK
- [x] JamesH1410 - Avalanche UK
- [x] LlordFlashheart - Avalanche UK
- [x] MARKYB0Y - Avalanche UK
- [x] fitex2001 - WARLOCKS CAN'T JUMP XB1
- [x] Jaren Malphur - Cry Havoc and let slip the dogs of war
- [x] Tor Kallon - Hezen Protective Group
- [x] Rebeccaryan - Dames Of Destiny Vie
- [x] Steeldiver54 (4611686018428496131) - Legαcy (3831237)
- [x] EdinMarty (4611686018470143321) - AVA

# Awaiting details

- John Wheeldon

**Comment by mattybeard** [comment]
Will close until updated

**Comment by benedfit** [comment]
Reopened as one of them has become a patron again

**Comment by benedfit** [comment]
Closing until more come in

**Comment by benedfit** [comment]
Reopened as I have one confirmed

**Comment by benedfit** [comment]
@mattybeard reopened as I got one confirmed, not sure if he is still on the site though

**Comment by benedfit** [comment]
@mattybeard another one
