### ISSUE TITLE
Insider program badges

### ISSUE THREAD

**Issue by benedfit** [newhighsco/destiny-clan-warfare#14]
# Confirmed

- [x] mr_e_us_1 - DoD Graveyard Shift
- [x] etsKi - Olympus Shields
- [x] Hiraeth Thought (4611686018461409471) - Revenge Is Ours (2004106) 
- [x] Suzame97 (4611686018451680790) - Revenge Is Ours (2004106) 
- [x] Diffusedmind (4611686018462681705) - Revenge Is Ours (2004106)
- [x] FRAGmethod HD (4611686018457363322) - Revenge Is Ours (2004106)
- [x] Smokedm (4611686018437148962) - Revenge Is Ours (2004106)
- [x] Morge64 (4611686018431916280) - Revenge Is Ours (2004106)
- [x] rnz (4611686018467188198) - X1 Light (187128)
- [x] | 2FAST4U | (4611686018443949599) - Revenge Is Ours (2004106)
- [x] stoppard stop - RIO
- [x] RNZ_CA (4611686018433336616) - Destiny Dads Yolo (1072888)
- [x] IronMikeActual (4611686018445565206) - Revenge Is Ours (2004106)
- [x] Hanxa (4611686018429103082) - Tomorrow Comes Today (1671951)
- [x] Roadkillooops (4611686018463747240) - Pink Fluffy Pineapple (2976198)
- [x] The Fish Boxer (4611686018432353429) - Elder Scrotes (1207188)
- [x] MsLDubu7 (4611686018463036241) - Revive Me in 5 (3012353)
- [x] notchdog10814 (4611686018446761648) - Dads of Destiny Relics (1151374)
- [x] N0OneUKn0w (4611686018458491684) - Rise of the Fall (3700850)
- [x] Aldar13 (4611686018465086194) - Renegades Rising (3190505)
- [x] ChristaRose (4611686018478553009) - Foreign fighters united (3264389)
- [x] W_o_M_a_N_ (4611686018488616049) - The Deadbeat Retreat (3449618)
- [x] UncleDrMrBaby (4611686018445591922) - Dip Your Cabals In It (1621365)
- [x] II PaRaNoYa II (4611686018437158593) - The Ghosts of Saint-14 (3777179)
- [x] KrypTix10 (4611686018462157358) - Rise of the Renegades (3190505)
- [x] macdd_01 (4611686018439648431) - Unknown Redux (1617786)

# Awaiting details

- ~~TerraBorn (4611686018433383596) - Rise of the Fall (3700850)~~ **PAYMENT DECLINED**

**Comment by mattybeard** [comment]
Closed until we get some more.

**Comment by benedfit** [comment]
I need to add the next batch of names

**Comment by benedfit** [comment]
- [ ] Hiraeth Thought (4611686018461409471) - Revenge Is Ours (2004106) 
- [ ]

**Comment by benedfit** [comment]
CC @mattybeard

**Comment by benedfit** [comment]
CC @mattybeard

**Comment by benedfit** [comment]
cc @mattybeard

**Comment by mattybeard** [comment]
Up to date

**Comment by benedfit** [comment]
@mattybeard one more confirmed

**Comment by mattybeard** [comment]
Up to date

**Comment by benedfit** [comment]
@mattybeard two more confirmed

**Comment by mattybeard** [comment]
Up to date

**Comment by benedfit** [comment]
@mattybeard two more

**Comment by benedfit** [comment]
Closing until more come in

**Comment by benedfit** [comment]
Reopening ready for new batch of Patrons

**Comment by benedfit** [comment]
@mattybeard few new ones here

**Comment by benedfit** [comment]
@mattybeard one more added

**Comment by benedfit** [comment]
@mattybeard one more added
