### ISSUE TITLE
LastUpdatedCacheTime

### ISSUE THREAD

**Issue by mattybeard** [newhighsco/destiny-clan-warfare#184]
- [x] Clan/GetAllClans
- [x] Clan/GetAllMembers
- [x] Event/GetAllEvents
- [x] Component/GetAllModifiers
- [x] Component/GetAllMedals
- [x] Component/GetAllClanMedals
- [x] Leaderboard/GetLeaderboard
- [x] Leaderboard/GetClanLeaderboard
- [x] Leaderboard/GetAllPlayersHistory
- [x] Leaderboard/GetPreviousClanLeaderboard

**Comment by mattybeard** [comment]
- [ ] Expose the lastupdatetimes

**Comment by benedfit** [comment]
Closed by #196
