### ISSUE TITLE
JSON requirements

### ISSUE THREAD

**Issue by benedfit** [newhighsco/destiny-clan-warfare#638]
- [x] Could the JSON be in `camelCase` rather than `PascalCase`?

If the tool that generates the JSON supports this, and it doesn't negatively impact the time to generate then this would help with some uniformity issues in the JavaScript

- [x] Could all ID fields be served as strings?

Due to the way Next handles routing, any `number` used in a URL has to be cast to a `string` so this would remove the need for some extra code in the JavaScript

- [ ] How, if at all, are we going to handle divisions?
- [x] `CurrentEvent/ClanLeaderboard.json` additions/changes:
  - [x] `clanId` can become `id` for brevity
  - [x] Add `name`
  - [x] Add `lastUpdated`
  - [x] Add `size` - count of total clan members
  - [x] Add `active` - count of clan members who have completed a match in the current event
  - [x] Add `avatar` (value in fields refers to [field name in old JSON](https://github.com/newhighsco/destiny-clan-warfare/blob/data-backup/data/Clan/GetAllClans.json)):
     ```
     avatar: {
       fill: 'backgroundColor',
       background: { fill: 'emblemColor2', src: 'backgroundIcon' }
       foreground: { fill: 'emblemColor1', src: 'foregroundIcon' }
     }
     ```

- [ ] Additional current event JSON for each clan `/CurrentEvent/Clan/{id}.json` containing the same data as seen in `CurrentEvent/ClanMembersLeaderboard.json`:
  - [x] `clanId` can be dropped as we are know this from the filename
  - [x] `membershipId` can become `id` for brevity
  - [x] Add `name`
  - [x] Add `avatar` - just containing bungie.net image URL
  - [x] `rank` to become rank within clan leaderboard
  - [x] Add `overall` to show overall event rank - TBC if we display this, so if it takes a while to calculate we can drop
  - [x] `gamesPlayed` can become `games` for brevity
  - [x] `gamesWon` can become `wins` for brevity
  - [x] `totalScore` can become `score` for brevity
  - [x] `matches` can be dropped, as I'll get those from `/CurrentEvent/ClanMember/{membershipId}.json`
  - [ ] `lastUpdated` is still needed for each member

**Comment by mattybeard** [comment]
If an ID can't be a string for an efficiency my side, I've added a "str" equivalent for your usage. I'll remove my ID in the future from the extract.

**Comment by benedfit** [comment]
- [ ] `/{id}/Tournament.json`
  - [ ] Add `description`
  - [ ] Add `startDate`
  - [ ] Add `endDate`
  - [ ] Add `tense` - are you still calculating this, or would you like me to handle it using the dates?
  - [ ] Can `bonus` be appended to `modifiers` so we have one array?
  - [ ] Add `stats`
  ```
  [
    { name: 'Total clans', value: number },
    { name: 'Total active', value: number },
    { name: 'Total games', value: number }
  ]
  ```

**Comment by benedfit** [comment]
- [x] `/{id}/ClanLeaderboard.json` - looking good ⭐
