### ISSUE TITLE
Insider program modifiers

### ISSUE THREAD

**Issue by benedfit** [newhighsco/destiny-clan-warfare#65]
# Confirmed

- [x] mr_e_us_1: "Pew...Pew...Pew" - Bonus for precision kills with a pulse rifle
- [x] etsKi: "Raid Master" - Bonus points for kills with a Raid weapon
- [x] Hiraeth Thought: "Abuse of Power" - Penalty for using Power Weapons
- [x] Suzame97: "20/20" - Bonus points for precision kills with a sniper
- [x] jkibbe: "Boy scout" - Get bonus points for scout rifle kills
- [x] Diffusedmind: "Not So Super" - Suffer a penalty and lose points for any super ability kill
- [x] FRAGmethod HD: "Frag & Tag" - Bonus for grenade or melee kill
- [x] stoppard stop: "Stop the stopper" - Bonus points for ending an enemy killstreak
- [x] Smokedm: "Automatic lockdown" - Lose points off your total score for each kill with an auto rifle.
- [x] Morge64: "Supers 2.0" - Bonus points for super kills with the new Destiny 2 supers (Sentinel, Dawnblade and Arcstrider)

# Awaiting details

- IronMikeActual
- Matt Thomas

**Comment by mattybeard** [comment]
Up to date.

**Comment by benedfit** [comment]
Closing until more come in
